apiVersion: runway.aa.com/v1alpha1
kind: WebApp
metadata:
  name: autopilot-mcp-gateway-nonprod
  annotations:
    enableCloudIngress: "true"
    backstageName: autopilot-mcp-gateway
  labels:
    app-id: autopilot-mcp-gateway
    aa-app-shortname: APIMgmtGQL
    data-classification: nonpci
    environment: nonprod
spec:
  containerName: docker.aa.com/prod/autopilot-mcp-gateway
  containerTag: 'v0.0.1'
  port: 8000
  healthCheck:
    endpoint: /health
    enabled: True
    port: 8000
  secretProviders:
    - vault:
        vaultNamespace: automation/apimgmtgql-autopilotnp-p
        secretEngineMount: secrets
        secretPath: nonprod
  autoscale:
    minimum: 1
    maximum: 2
  reachableServices:
    - aa-graph-mcp-server-nonprod.autopilot-nonprod.svc.cluster.local
    - caas-mcp-nonprod.entinfauto-nonprod.svc.cluster.local