apiVersion: runway.aa.com/v1alpha2
kind: Ephemeral
metadata:
  name: navigatoragentsephemeral
  annotations:
    enableCloudIngress: "true"
    backstageName: autopilot-mcp-gateway
  labels:
    app-id: autopilot-mcp-gateway-nonprod
    runway.aa.com/aa-app-shortname: APIMgmtGQL
    data-classification: nonpci
    environment: nonprod
spec:
  repo: autopilot-mcp-gateway
  maxEphemerals: 10
  maxDaysWithoutUpdate: 4
  template:
    containerName: docker.aa.com/nonprod/autopilot-mcp-gateway
    containerTag: placeholder
    port: 8000
